### ISSUE TITLE
JSX Support

### ISSUE THREAD

**Issue by zaalbarxx** [UnrefinedBrain/vue-metamorph#21]
Hi!
Working with your project right now, it's really fantastic work (did something similar with fork of `vue-codemod`, but this one is much cleaner). But one thing that may be missing here is the support for JSX (possibly by checking script `lang` attribute, if it is `jsx` or `tsx`). Right now parsing fails for files which do contains JSX. I could take a look at this when I'm free, but maybe this is just a matter of couple lines of code, I guess Babel does not have any problem with parsing JSX with proper plugin.

Edit: Actually it may be just a matter of adding `jsx` plugin to the list of plugins.

**Comment by UnrefinedBrain** [comment]
Yep looks like adding `jsx` to the plugin list works! I'll cut a new release momentarily

**Comment by UnrefinedBrain** [comment]
Try 2.0.13 and let me know if it works for you

**Comment by zaalbarxx** [comment]
Thanks a lot @UnrefinedBrain , works well. Have a nice day :)
