### ISSUE TITLE
Adding new Nodes to script AST possible?

### ISSUE THREAD

**Issue by kassuro** [UnrefinedBrain/vue-metamorph#9]
I just started to explore the project and I really like it so far!

So my use case would be that I want to exchange a method with a new one from a different module and I would like to add the new import with the codemod as well.

I couldn't find a hint in the docs if it's possible to add a new node to the script AST and if so, how it should be done.

I've seen the `scriptBuilders` plugin, but I'm not sure how I should use it.

**Comment by UnrefinedBrain** [comment]
Yes you can mutate the AST however you want, including adding and removing nodes. For adding a node to a function body, for example, you can use `node.body.push()` or `node.body.splice()` or any other method of object mutations.

I guess I have a documentation gap here - I did create helper methods for inserting new imports under `astHelpers`. There's `astHelpers.createNamedImport`, `astHelpers.createDefaultImport`, and `astHelpers.createNamespaceImport` depending on which import type you want. All will re-use existing import statements if they exist

`scriptBuilders` methods will create node for you, but you still need to insert them into the AST yourself:

```ts
const exchangeMethod: CodemodPlugin = {
  type: 'codemod',
  name: 'new-method',
  transform(scriptASTs, _sfcAST, _filename, { astHelpers, scriptBuilders }) {
    let count = 0;
    for (const scriptAST of scriptASTs) {
      let shouldAddImport = false;

      // find call sites with the old method
      astHelpers
        .findAll(scriptAST, {
          type: 'CallExpression',
          callee: {
            type: 'Identifier',
            name: 'oldMethod',
          }
        })
        .forEach((node) => {
          count++;
          shouldAddImport = true;
          // replace the callee by mutating the node
          node.callee = scriptBuilders.identifier('newMethod');
        });

      if (shouldAddImport) {
        astHelpers.createNamedImport(scriptAST, '@/path/to/file', 'newMethod');
      }
    }

    return count;
  },
}
```

**Comment by UnrefinedBrain** [comment]
I'm working on a vue 2 --> vue 3 upgrade tool if you want to see some more examples while I work on adding more content to the docs: https://github.com/UnrefinedBrain/vue-upgrade-tool/tree/master/src/plugins

**Comment by kassuro** [comment]
Thanks for the fast response! This definitely helps me.
And your code mod project for the upgrade might be really helpful in the coming weeks. Currently working towards the transition.
