### ISSUE TITLE
isJsx state should also consider the vue component with render method

### ISSUE THREAD

**Issue by haoliangwu** [UnrefinedBrain/vue-metamorph#93]
the [isJsx](https://github.com/UnrefinedBrain/vue-metamorph/blob/32d5eaf35e0dfb520680e84a834edc99bd9f2550/src/parse/vue.ts#L45) here should also consider the following scenario for making `@babel/parser` support jsx automatically, eg:
```vue
<script>
export default {
   render(h) {
      return h(tag, attribute, [
      <bTypography class="bButton-contents" variant={textVariant} component="span">
        {contents}
      </bTypography>,
    ])
   }
}
</script>
```
anyway, it is probably a edge case here that mixing usage of `h` and `jsx` syntax.

**Comment by UnrefinedBrain** [comment]
does it work if you make it `<script lang="jsx">` ?

**Comment by UnrefinedBrain** [comment]
I don't want to parse everything as jsx all the time, because there's a typescript cast syntax that intersects with jsx, so I made it look for `lang="jsx"` or `lang="tsx"` in SFCs to support both cases

**Comment by haoliangwu** [comment]
@UnrefinedBrain 
> does it work if you make it <script lang="jsx"> ?
yes, it works now, thanks for help.

> I don't want to parse everything as jsx all the time, because there's a typescript cast syntax that intersects with jsx, so I made it look for lang="jsx" or lang="tsx" in SFCs to support both cases
I got your point here and I agree with that. 

Actually, the issue here is a edge case even the project I am migrating, so I will close this issue.
